main:
  params: [event]
  steps:
    - init:
        assign:
          - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - region: "us-central1"
          - message_data: ${base64.decode(event.data.message.data)}
          - payload: ${json.decode(message_data)}
          - results: {}

    - log_start:
        call: sys.log
        args:
          severity: INFO
          text: ${"Starting social fan-out for message"}

    - parallel_publish:
        parallel:
          shared: [results]
          branches:
            - linkedin_branch:
                steps:
                  - call_linkedin:
                      try:
                        call: http.post
                        args:
                          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/publish-linkedin"}
                          auth:
                            type: OIDC
                          body:
                            content: ${payload.linkedin_content}
                            audio_url: ${default(payload.audio_url, "")}
                        result: linkedin_response
                      retry:
                        predicate: ${retry_predicate}
                        max_retries: 3
                        backoff:
                          initial_delay: 2
                          max_delay: 60
                          multiplier: 2
                  - save_linkedin_result:
                      assign:
                        - results.linkedin: ${linkedin_response.body}

            - threads_branch:
                steps:
                  - call_threads:
                      try:
                        call: http.post
                        args:
                          url: ${"https://" + region + "-" + project_id + ".cloudfunctions.net/publish-threads"}
                          auth:
                            type: OIDC
                          body:
                            content: ${payload.threads_content}
                        result: threads_response
                      retry:
                        predicate: ${retry_predicate}
                        max_retries: 5
                        backoff:
                          initial_delay: 3
                          max_delay: 120
                          multiplier: 2
                  - save_threads_result:
                      assign:
                        - results.threads: ${threads_response.body}

    - log_complete:
        call: sys.log
        args:
          severity: INFO
          text: ${"Fan-out complete. Results: " + json.encode_to_string(results)}

    - return_results:
        return: ${results}

retry_predicate:
  params: [e]
  steps:
    - check_error:
        switch:
          - condition: ${e.code == 429}
            return: true
          - condition: ${e.code >= 500}
            return: true
    - return_false:
        return: false
